### ISSUE TITLE
Keepalive method for LiveTranscriptionClient

### ISSUE THREAD

**Issue by ThindalTV** [deepgram/deepgram-dotnet-sdk#112]
## Proposed changes

Add a keepalive method to the livetranscriptionclient.

## Context

Right now we need to do a SendData call with the keepalive message manually, which while not hard isn't obvious.

## Possible Implementation

Add an async Task KeepAlive() to ILiveTranscriptionClient

**Comment by lukeocodes** [comment]
Yeh we need this, and have been telling clients how to do it with a SendData call!
