### ISSUE TITLE
Match .NET package dependencies to .NET version

### ISSUE THREAD

**Issue by kirk-marple** [deepgram/deepgram-dotnet-sdk#117]
## Proposed changes

I'd like to request that the Microsoft.* and System.* package references use 6.x for the .NET 6.0 version of the Deepgram assembly.

<PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />

## Context

There are compatibility issues, in Azure Functions specifically, when bringing in 7.x assemblies, and we've had to avoid upgrading any packages which pull in .NET 7 assemblies. (Commonly, using the newer version of the Extensions.* packages seem to cause problems.)

## Possible Implementation

Change .csproj to only reference 6.x assemblies when building for .NET 6.

**Comment by lukeocodes** [comment]
hey @kirk-marple we'd welcome a PR :)

**Comment by CopperBeardy** [comment]
is this with the V3 or the V2 Nuget packages?

**Comment by CopperBeardy** [comment]
V2 and V3 both have all current features supported(need to go back and refactor to add the changes thindal made), v2 does not have .net7 support in it.

**Comment by ThindalTV** [comment]
I'll deal with it once the csproj CI/CD PR is merged.

**Comment by kirk-marple** [comment]
@lukeocodes @ThindalTV Added a PR for this, and a couple cleanup things I noticed.

@CopperBeardy I believe it was for v3 package.  I was still using 2.2.0 and couldn't upgrade to 3.1.0 because we're still using .NET 6.

**Comment by jpvajda** [comment]
I believe this issue is resolved now as i see the change was merged in from #124. I'll close if someone can confirm.
