### ISSUE TITLE
Console.WriteLine in the LiveTranscriptionClient creates unwanted noise in the console output

### ISSUE THREAD

**Issue by acidbubbles** [deepgram/deepgram-dotnet-sdk#134]
## What is the current behavior?

I have logs I cannot control.

## Steps to reproduce

You can see the code here: https://github.com/deepgram/deepgram-dotnet-sdk/blob/460a300b3cc631739dc48403e31966c0633410a6/Deepgram/Clients/LiveTranscriptionClient.cs#L254

Here are two example messages I receive that I consider "normal":

> Deepgram did not provide a response message within the timeout window. See https://dpgr.am/net0000
> Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001

## Expected behavior

Either use the ILogger implementation, or provide an event that I can then control to avoid filling up logs with 

## Please tell us about your environment

- Windows 11
- C#

**Comment by CopperBeardy** [comment]
this has been corrected in the coming V4
