### ISSUE TITLE
Deserialize speaker as an int not a string

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-dotnet-sdk#145]
## Proposed changes

See this PR for an attempt to make this change https://github.com/deepgram/deepgram-dotnet-sdk/pull/144
This approach was introduced in https://github.com/deepgram/deepgram-dotnet-sdk/pull/138

This is consider a breaking change and will need to wait for a major version. Changing from `string` to `int` will offer users of the SDKs a better overall experience in the introduction of this feature our choice of `string` wasn't ideal and we want to change it an `int`. 

## Work Around
The workaround to this is to use `int result = Int32.Parse(input);`

**Comment by dvonthenen** [comment]
Addressed in this PR: https://github.com/deepgram/deepgram-dotnet-sdk/blob/main/Deepgram/Models/PreRecorded/v1/Word.cs#L40

Will be available in the first release of `v4`.
