### ISSUE TITLE
Sentiment Analysis (Listen) supported

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-dotnet-sdk#152]
* old param `analyze_sentiment` should be kept for backwards compatibility cases.
* new param `sentiment` added for sentiment analysis  for `/listen` requests.

See [Beta Docs](https://developers.deepgram.com/reference/audio-intelligence-apis) for more information on how this API will operate.

**Comment by dvonthenen** [comment]
This should be implicitly implemented after fixing the Schema and Response objects in this PR:
https://github.com/deepgram/deepgram-dotnet-sdk/pull/204

Will create example applications to prove this is the case.

**Comment by dvonthenen** [comment]
Created separate issue to track Prerecorded SITS unit test and examples:
https://github.com/deepgram/deepgram-dotnet-sdk/issues/220

Closing this implementation issue out.
