### ISSUE TITLE
RFC: SDK Re-architecture Approach

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-dotnet-sdk#159]
## Considerations 

* C-Sharp is object oriented. 
* In Dotnet separation of concerns Is important.  
* Deepgram cares about the .NET developer experience and wants our new .NET SDK to appeal to .NET Developers and give them what they expect. The Current SDK is more JavaScript inspired. 
* Deppgram product nomenclature is important. We should ensure we have similar naming conventions at the API level and ensue the client naming is consistence across SDKS.

## API & Client names
 
- on prem API = `onpremclient` 
- manage API  = `manageclient`
- listen  API = `prerecordedclient`  & `liveclient`
- read API =   `analyzeclient`
- speech API  = `speakclient` (future)

## Release Approach

- Alpha versions made available for feedback and bug fixing
- Beta version made available for feedback and bug fixing
- GA version made available for general adoption and migration to new SDK

## References
* See this repo for architecture approach: https://github.com/deepgram/deepgram-sdk-architecture/
* Refer to Deepgram API Reference for API functionality https://developers.deepgram.com/reference/authentication
*  https://github.com/CopperBeardy/deepgrampropsosedSDKChangesRough - @CopperBeardy 

---- 
# Proposal 

To be determined

**Comment by dvonthenen** [comment]
I got a chance to take a look at the project, and kudos to @CopperBeardy and @ThindalTV (and anyone else that I missed who has contributed to the project) for working on this. First, the project is in good shape and is healthy! It’s evident that a LOT of effort has been put into this, and it shows!

I have been taking a look at the [architecture guidelines](https://github.com/deepgram/deepgram-sdk-architecture), the current state of the SDKs, and the guidance I got from John to reflect on things we want to accomplish in v4. Before we get into that, we need to define goals and non-goals. The big takeaway from the goals/non-goals is: Clearly defined interfaces mean the unlying implementation can change an infinite number of times.

### Goals:
- SDK architecture alignment with other SDKs
- Reduce complexity
- (Hopefully) Increase ease of use
- Ultimately, things that address interface or packaging changes

### Non-Goals (Non-Architecture Related “Things”)
- Bug Fixes (example, HTTP Timeout)
- Lower Level Features (example, UtteranceEnd)
- Examples (example, Microphone Transcription)
- Specific Implementations of “Things”

This is to say that we will do bug fixes, examples, enhancements, etc for `v4`. It's just not the goal for this post. Those discussions can be had on individual PRs for those individual features, fixes, etc.

## More Details

I took some time to think about this; below are the larger items that can help users consume the project more easily.

- Add some organization - Less to do with code changes, but more like project structure and organization. The project would have a lot of benefits in organizing, as in creating discrete folders, by function (Prerecorded, Live, Manage, Analyze) like the other SDKs have. For example, Models would look like:
  - Models/Prerecorded/v1
  - Models/Live/v1
  - Models/Manage/v1
  - Models/Analyze/v1 (to be added)
- Collapse some of the granularity of the "Manage" clients. Currently, there are clients for Projects, Keys, etc. Most users tend to stick within a given function group. They typically perform a bunch of prerecorded operations, etc, or in this case, managing projects, users, etc, where you don’t need separate clients.
- Look at providing “convenience” (all in one) dot notation like JS, Python, Go have. This isn't required to be used by the end user as they can get at the classes directly, but this is more of just providing a simple way to access methods covered in the architecture repo. I would probably not use them myself, but again merely some unity across the SDKs.
  - Example: `deepgram.listen.prerecorded.transcribe_file()`
- Design the ability to handle API versions. This is partially implemented in items #1 and #2, but we need to allow `v1/listen`, `v2beta1/listen`, `v2/listen`, etc to coexist in the same project. Python and Go have this implemented already in their latest release versions.
  - This does not need to be completely implemented in v4, but rather, things should be put into place that allow this to happen without breaking the interface definitions.
- Allow freeform query parameters and headers for “function”-type as in Live, Prerecorded, Manage, and Analyze.
- All connections (Websocket and HTTP(S)) should contain timeouts and be cancelable.
- Good to see unit tests (yay!), but add another project containing examples.

These changes don’t affect logical code too much, but rather just the organization of the project. Please read through, feedback is always welcome, and happy to discuss this further. I'm always available in Discord for anyone who wants to reach out to talk through some of these items.

It's very cool to be working on the project with the community here, and kudos to all the hard work done in the repo! Cheers!

**Comment by dvonthenen** [comment]
I forgot to mention that we are going to move the active development branch from `v4-alpha` (and `dotnet-sdk-v4` - doesn't look like that has been updated in a while) to use `main`. I created a `release-v3` that will accept patch releases, bug fixes, security fixes, etc. The goal is to have `v4` completed and out in the next 4 weeks... let's say March 1 for GA and Feb 21 for the first alpha.

**Comment by dvonthenen** [comment]
closing since posted

**Comment by dvonthenen** [comment]
Pinned to the repo for visibility.
