### ISSUE TITLE
Add support for `UtteranceEnd` message

### ISSUE THREAD

**Issue by jjmaldonis** [deepgram/deepgram-dotnet-sdk#160]
## Proposed changes

Deepgram sends a `{"type": "UtteranceEnd"}` message when the `utterance_end_ms=1000` query parameter is included in a streaming request. The .NET does not support this message type.

## Context

A customer had to create their own internal version of the .NET SDK in order to implement this. `utterance_end_ms` is becoming a common need.

## Possible Implementation

Implement similar to the other `{"type": ...}` messages.

## Other information

See docs here: https://github.com/nikolawhallon/temp-utterance-end#utteranceend-and-its-limitations

**Comment by dvonthenen** [comment]
This appears to have been implemented in the initial `v4` PR here:
https://github.com/deepgram/deepgram-dotnet-sdk/pull/188
