### ISSUE TITLE
Expose the 'extra' parameter in PrerecordedTranscriptionOptions

### ISSUE THREAD

**Issue by doc** [deepgram/deepgram-dotnet-sdk#171]
## Proposed changes

I propose adding an `Extra` property to the  `PrerecordedTranscriptionOptions` class that allows users of the SDK to include additional metadata in the request with the expectation that it will be echo'd back to them in the response. This is already a feature of the REST API, just needs to be exposed in the SDK. 

## Context

From https://developers.deepgram.com/docs/extra-metadata:

"Extra Metadata allows you to label your requests for the purpose of identification in downstream processing. Deepgram’s Extra Metadata feature allows you to attach arbitrary key-value pairs to your API requests that are attached to the API response for usage in downstream processing.

Extra metadata is limited to 2048 characters per key-value pair."

This feature is critical to our processing pipeline.

**Comment by dvonthenen** [comment]
This should have been addressed in the Prerecorded Audit.
https://github.com/deepgram/deepgram-dotnet-sdk/blob/main/Deepgram/Models/PreRecorded/v1/PrerecordedSchema.cs#L99

Will be available on the first release of `v4`.
