### ISSUE TITLE
Add support for `SpeechStarted` via `vad_events` feature

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-dotnet-sdk#180]
A new feature to the Deepgram API allows for a user to better determine when speech has started in an audio live stream. We want to add support for this into the .NET SDK. 

See Docs for more details: https://developers.deepgram.com/docs/start-of-speech-detection

**Comment by dvonthenen** [comment]
Merged https://github.com/deepgram/deepgram-dotnet-sdk/pull/253
