### ISSUE TITLE
Remove VTT and SRT Code from .NET

### ISSUE THREAD

**Issue by dvonthenen** [deepgram/deepgram-dotnet-sdk#211]
## Proposed changes

Remove VTT and SRT Code from .NET

## Context

NA

## Possible Implementation

NA

## Other information

NA

**Comment by dvonthenen** [comment]
Merged PR https://github.com/deepgram/deepgram-dotnet-sdk/pull/225. Closing

**Comment by LefanTan** [comment]
Apologies for asking in an older thread, but how should devs using the .NET sdk convert `PreRecorded` responses to VTT/SRT? 

Seems like the most effective way is to dig through the JS implementations and translate them to c# code?

**Comment by dvonthenen** [comment]
We have two different implementations of the captions (in Python and JavaScript). You could just invoke the JavaScript or Python projects without needing to convert and run native C# code. We broke the VTT and SRT into standalone projects in hopes we don't need to implement the functionality in every language.

I would like to understand the use case a little more. Would just invoking the python or JS libraries work for you?

If we do implement a C# version based on demand, it would probably also be a standalone library similar to what we did for the microphone library.
