### ISSUE TITLE
support the `callback_method` 

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-dotnet-sdk#232]
Support the use of the following:

* callback_method `boolean`
* Enables a callback method. Default: false

**Comment by jpvajda** [comment]
@dvonthenen I've added this issue for us to add callback_method support to the .NET SDK.

**Comment by dvonthenen** [comment]
This is implemented in `v4` and we should get an alpha out hopefully really soon.

**Comment by dvonthenen** [comment]
This is implemented already in v4. Closing.
