### ISSUE TITLE
The GetUsageSummaryOptions class is out of sync with the API

### ISSUE THREAD

**Issue by MichaelJolley** [deepgram/deepgram-dotnet-sdk#28]
- [ ] The `Model` property should be an array of string rather than a string

Documentation for this endpoint lives at https://developers.deepgram.com/api-reference/#usage-summary

**Comment by MaryJoStaebler** [comment]
Working on this sibling issue to help test the other.   Also I will have to add in. Json formatter to get the right date format for the api call.
