### ISSUE TITLE
Latest 4.0.0 SDK is referencing .NET 8 assemblies in .NET 6 target

### ISSUE THREAD

**Issue by kirk-marple** [deepgram/deepgram-dotnet-sdk#280]
## What is the current behavior?
Latest v4 SDK is referencing .NET 8 assemblies in .NET 6 target.

Looks like the .NET 7 target is correct, and referencing .NET 7 assemblies, but .NET 6 target is broken.

## Steps to reproduce
![image](https://github.com/deepgram/deepgram-dotnet-sdk/assets/13594550/8aa7fc63-774f-49e8-928d-dbc885e75feb)

## Expected behavior
Not to reference .NET 8 assemblies in .NET 6 target.

**Comment by dvonthenen** [comment]
That's definitely an oops. Will have a patch for this shortly.

**Comment by dvonthenen** [comment]
A PR is posted. Will get it reviewed tomorrow and have a patch release for it.

**Comment by dvonthenen** [comment]
This should be in nuget in the next couple of minutes.
https://github.com/deepgram/deepgram-dotnet-sdk/releases/tag/4.0.1
