### ISSUE TITLE
Add support for Searches in Listen V1 Websocket Channels

### ISSUE THREAD

**Issue by ElliotEserin** [deepgram/deepgram-dotnet-sdk#323]
## Proposed changes

The Deepgram API supports searches in its live audio transcribing (WebSocket) endpoints, however, the .NET SDK currently only supports this functionality for REST endpoints.

## Context

The SDK would better reflect the API and provide supported functionality to the user.

## Possible Implementation

It's my understanding that it would be the same as what is currently implemented for the REST model, however I may be wrong on this assumption.

## Other information

I would be happy to implement this and create a PR if it would be useful.

**Comment by dvonthenen** [comment]
Hi @ElliotEserin 

Is this what you are looking for?
https://github.com/deepgram/deepgram-dotnet-sdk/blob/main/Deepgram/Models/Listen/v1/WebSocket/LiveSchema.cs#L197-L204

**Comment by ElliotEserin** [comment]
Hi, thanks for the quick reply!
Currently it seems like you can provide searches in the LiveSchema, but there isn't currently a way to read the response because searches aren't included in the channel record https://github.com/deepgram/deepgram-dotnet-sdk/blob/main/Deepgram/Models/Listen/v1/WebSocket/Channel.cs Unless they are accessible somewhere else and I've missed it

**Comment by dvonthenen** [comment]
ahhhh gotcha. will take a look. thanks for the detail.

**Comment by ElliotEserin** [comment]
Great, thank you!
