### ISSUE TITLE
Concurrent users on Azure Standard_NC4as_T4_v3

### ISSUE THREAD

**Issue by gsrat1** [deepgram/deepgram-dotnet-sdk#330]
Hi,

Unfortunately we cannot use deepgram with our sensitive data because you only have US servers.
We need a service hosted in Australia.

I was wondering if we were to deploy on a server that meets the minimum requirements like the following:
Azure Standard_NC4as_T4_v3

How many concurrent requests would it be able to handle?

Thanks

Gishan

**Comment by dvonthenen** [comment]
hi @gsrat1 

There maybe some options available. If you want to either contact me on Discord (https://dpgr.am/discord), I can put you in contact with someone to can help navigate the options with you.

Since this isn't an SDK problem, closing this issue.
