### ISSUE TITLE
IListenWebSocketClient is missing SendFinalize API

### ISSUE THREAD

**Issue by sgodin** [deepgram/deepgram-dotnet-sdk#332]
## What is the current behavior?
SendFinalize exists on Deepgram/Clients/Listen/v1/WebSocket/Client.cs, but is not availabe via the IListenWebSocketClient

**Comment by dvonthenen** [comment]
Hi @sgodin 

Will include that in the next release. In the meantiem, you can copy and paste the contents of the function and just sand the message directly

**Comment by sgodin** [comment]
Yup that's what I'm doing.  :)  Thanks for quick response.

**Comment by dvonthenen** [comment]
PR https://github.com/deepgram/deepgram-dotnet-sdk/pull/334 merged. Will be available in the 4.3.4 release.
