### ISSUE TITLE
Implement Analyze Text

### ISSUE THREAD

**Issue by kaller01** [deepgram/deepgram-dotnet-sdk#335]
## Proposed changes
Deepgram supports sending in text to the read endpoint, add the method `AnalyzeText`.

## Context
In my use case, I already have the content as a string, and currently I would have to convert to file encoding.

## Possible Implementation
Introduce `TextSource` and `AnalyzeText` and `AnalyzeTextCallback` which are based of the equivalent `UrlSource` methods.

**Comment by dvonthenen** [comment]
this will be available in the upcoming release! thanks again @kaller01
