### ISSUE TITLE
Add .NET standard 2.0 target

### ISSUE THREAD

**Issue by yi-fan-song** [deepgram/deepgram-dotnet-sdk#7]
I would like to use this sdk in a .NET Framework 4.8 project, but currently the targets are netcore3.1, .net 5.0, .net 6.0. Is netstandard 2.0 something that can be supported?

I've got a local diff that compiles to netstandard 2.0 target that I'm using for now.

**Comment by MichaelJolley** [comment]
@yi-fan-song, we're totally up for that. Feel free to submit a PR to add that.

**Comment by yi-fan-song** [comment]
@MichaelJolley I'm not using the sdk anymore, I needed a way to make it hit a different url so I just have a similar service in my project. I still submitted the PR in case you'd be interested in it.
